version: '3.9'
services:
  web:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    command: bash -c "bundle install && ruby server.rb"
    environment: 
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    command: bash -c "bundle exec sidekiq -r ./app/worker.rb"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data-rebase-labs:/var/lib/postgresql/data

volumes:
  labs-gems:
